# Generated by Django 2.2.6 on 2020-12-22 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='choice_five',
        ),
    ]
