# Generated by Django 2.2.6 on 2020-12-25 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0002_remove_quiz_choice_five'),
    ]

    operations = [
        migrations.CreateModel(
            name='save_user_answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit', models.CharField(max_length=200)),
            ],
        ),
    ]
