# Generated by Django 2.2.6 on 2020-12-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0003_save_user_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('choice_one', models.CharField(max_length=200)),
                ('choice_two', models.CharField(max_length=200)),
                ('choice_three', models.CharField(max_length=200)),
                ('choice_four', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='save_user_answer',
        ),
    ]
